package sourcepac;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

/**
 * The ScheduleGenerator class
 * @author Chris Davidson
 * @version 5/16/2011
 *
 */
public class ScheduleGenerator {
  
  /**
   * The Schedule being generated by this class.  Contains a title
   * and courses read in from a .csv file.
   */
  private Schedule my_schedule;

  public ScheduleGenerator() {
    my_schedule = new Schedule();
  }
  
  public void importSchedule(String fileName) {
    final File inputSchedule = new File(fileName);
    Scanner in = null;
    String current = "";
    String[] line = new String[8];
    CourseCopy course;
    try {
      in = new Scanner(inputSchedule);
    } catch (FileNotFoundException exception) {
      System.err.println("File not found");
    }
    while(in.hasNext()) {
      current = in.nextLine();
      if(!current.startsWith("%")) {
        break; // Skip all of the comments
      }
    }
    my_schedule.setTitle(current.substring(0, current.indexOf(',')));
    if(in.hasNext()) { // Skip the column headers
      current = in.nextLine();
    }
    while (in.hasNext()) {
      current = in.nextLine();
      line = current.split(",");
      course = new CourseCopy(line[0], line[1], line[2], 
                              Integer.parseInt(line[7]),
                              Integer.parseInt(line[5]),
                              Integer.parseInt(line[6]), line[3], 1);
      //Fix the above line when we decide on how to represent days
      my_schedule.addCourse(course);
    }
  }

  /**
   * Getter method for the Schedule being generated.  Contains no
   * relevant information if no Schedule has been imported.
   * @return The Schedule, generated or not.
   */
  public Schedule getSchedule() {
    return my_schedule;
  }

}
